enum Continent { EU, AS, NA, AF, AN, SA, OC }

class Country {
  final String? name;
  final String? nativeName;
  final String? dialingCode;
  final String? isoCode;
  final Continent? continent;
  final String? capital;
  final String? currency;
  final List<String>? languages;
  final String? emoji;
  final String? emojiUnicode;

  const Country({
    this.name,
    this.nativeName,
    this.dialingCode,
    this.isoCode,
    this.continent,
    this.capital,
    this.currency,
    this.languages,
    this.emoji,
    this.emojiUnicode,
  });

  @override
  bool operator ==(o) =>
      o is Country &&
      o.name == this.name &&
      o.nativeName == this.nativeName &&
      o.dialingCode == this.dialingCode &&
      o.isoCode == this.isoCode &&
      o.continent == this.continent;

  static const Country AD = Country(
    name: 'Andorra',
    nativeName: 'Andorra',
    dialingCode: '376',
    isoCode: 'AD',
    continent: Continent.EU,
    capital: 'Andorra la Vella',
    currency: 'EUR',
    languages: ["ca"],
    emoji: '🇦🇩',
    emojiUnicode: 'U+1F1E6 U+1F1E9',
  );
  static const Country AE = Country(
    name: 'United Arab Emirates',
    nativeName: 'دولة الإمارات العربية المتحدة',
    dialingCode: '971',
    isoCode: 'AE',
    continent: Continent.AS,
    capital: 'Abu Dhabi',
    currency: 'AED',
    languages: ["ar"],
    emoji: '🇦🇪',
    emojiUnicode: 'U+1F1E6 U+1F1EA',
  );
  static const Country AF = Country(
    name: 'Afghanistan',
    nativeName: 'افغانستان',
    dialingCode: '93',
    isoCode: 'AF',
    continent: Continent.AS,
    capital: 'Kabul',
    currency: 'AFN',
    languages: ["ps", "uz", "tk"],
    emoji: '🇦🇫',
    emojiUnicode: 'U+1F1E6 U+1F1EB',
  );
  static const Country AG = Country(
    name: 'Antigua and Barbuda',
    nativeName: 'Antigua and Barbuda',
    dialingCode: '1268',
    isoCode: 'AG',
    continent: Continent.NA,
    capital: 'Saint John\'s',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇦🇬',
    emojiUnicode: 'U+1F1E6 U+1F1EC',
  );
  static const Country AI = Country(
    name: 'Anguilla',
    nativeName: 'Anguilla',
    dialingCode: '1264',
    isoCode: 'AI',
    continent: Continent.NA,
    capital: 'The Valley',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇦🇮',
    emojiUnicode: 'U+1F1E6 U+1F1EE',
  );
  static const Country AL = Country(
    name: 'Albania',
    nativeName: 'Shqipëria',
    dialingCode: '355',
    isoCode: 'AL',
    continent: Continent.EU,
    capital: 'Tirana',
    currency: 'ALL',
    languages: ["sq"],
    emoji: '🇦🇱',
    emojiUnicode: 'U+1F1E6 U+1F1F1',
  );
  static const Country AM = Country(
    name: 'Armenia',
    nativeName: 'Հայաստան',
    dialingCode: '374',
    isoCode: 'AM',
    continent: Continent.AS,
    capital: 'Yerevan',
    currency: 'AMD',
    languages: ["hy", "ru"],
    emoji: '🇦🇲',
    emojiUnicode: 'U+1F1E6 U+1F1F2',
  );
  static const Country AO = Country(
    name: 'Angola',
    nativeName: 'Angola',
    dialingCode: '244',
    isoCode: 'AO',
    continent: Continent.AF,
    capital: 'Luanda',
    currency: 'AOA',
    languages: ["pt"],
    emoji: '🇦🇴',
    emojiUnicode: 'U+1F1E6 U+1F1F4',
  );
  static const Country AQ = Country(
    name: 'Antarctica',
    nativeName: 'Antarctica',
    dialingCode: '672',
    isoCode: 'AQ',
    continent: Continent.AN,
    capital: '',
    currency: '',
    languages: [],
    emoji: '🇦🇶',
    emojiUnicode: 'U+1F1E6 U+1F1F6',
  );
  static const Country AR = Country(
    name: 'Argentina',
    nativeName: 'Argentina',
    dialingCode: '54',
    isoCode: 'AR',
    continent: Continent.SA,
    capital: 'Buenos Aires',
    currency: 'ARS',
    languages: ["es", "gn"],
    emoji: '🇦🇷',
    emojiUnicode: 'U+1F1E6 U+1F1F7',
  );
  static const Country AS = Country(
    name: 'American Samoa',
    nativeName: 'American Samoa',
    dialingCode: '1684',
    isoCode: 'AS',
    continent: Continent.OC,
    capital: 'Pago Pago',
    currency: 'USD',
    languages: ["en", "sm"],
    emoji: '🇦🇸',
    emojiUnicode: 'U+1F1E6 U+1F1F8',
  );
  static const Country AT = Country(
    name: 'Austria',
    nativeName: 'Österreich',
    dialingCode: '43',
    isoCode: 'AT',
    continent: Continent.EU,
    capital: 'Vienna',
    currency: 'EUR',
    languages: ["de"],
    emoji: '🇦🇹',
    emojiUnicode: 'U+1F1E6 U+1F1F9',
  );
  static const Country AU = Country(
    name: 'Australia',
    nativeName: 'Australia',
    dialingCode: '61',
    isoCode: 'AU',
    continent: Continent.OC,
    capital: 'Canberra',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇦🇺',
    emojiUnicode: 'U+1F1E6 U+1F1FA',
  );
  static const Country AW = Country(
    name: 'Aruba',
    nativeName: 'Aruba',
    dialingCode: '297',
    isoCode: 'AW',
    continent: Continent.NA,
    capital: 'Oranjestad',
    currency: 'AWG',
    languages: ["nl", "pa"],
    emoji: '🇦🇼',
    emojiUnicode: 'U+1F1E6 U+1F1FC',
  );
  static const Country AX = Country(
    name: 'Åland',
    nativeName: 'Åland',
    dialingCode: '358',
    isoCode: 'AX',
    continent: Continent.EU,
    capital: 'Mariehamn',
    currency: 'EUR',
    languages: ["sv"],
    emoji: '🇦🇽',
    emojiUnicode: 'U+1F1E6 U+1F1FD',
  );
  static const Country AZ = Country(
    name: 'Azerbaijan',
    nativeName: 'Azərbaycan',
    dialingCode: '994',
    isoCode: 'AZ',
    continent: Continent.AS,
    capital: 'Baku',
    currency: 'AZN',
    languages: ["az"],
    emoji: '🇦🇿',
    emojiUnicode: 'U+1F1E6 U+1F1FF',
  );
  static const Country BA = Country(
    name: 'Bosnia and Herzegovina',
    nativeName: 'Bosna i Hercegovina',
    dialingCode: '387',
    isoCode: 'BA',
    continent: Continent.EU,
    capital: 'Sarajevo',
    currency: 'BAM',
    languages: ["bs", "hr", "sr"],
    emoji: '🇧🇦',
    emojiUnicode: 'U+1F1E7 U+1F1E6',
  );
  static const Country BB = Country(
    name: 'Barbados',
    nativeName: 'Barbados',
    dialingCode: '1246',
    isoCode: 'BB',
    continent: Continent.NA,
    capital: 'Bridgetown',
    currency: 'BBD',
    languages: ["en"],
    emoji: '🇧🇧',
    emojiUnicode: 'U+1F1E7 U+1F1E7',
  );
  static const Country BD = Country(
    name: 'Bangladesh',
    nativeName: 'Bangladesh',
    dialingCode: '880',
    isoCode: 'BD',
    continent: Continent.AS,
    capital: 'Dhaka',
    currency: 'BDT',
    languages: ["bn"],
    emoji: '🇧🇩',
    emojiUnicode: 'U+1F1E7 U+1F1E9',
  );
  static const Country BE = Country(
    name: 'Belgium',
    nativeName: 'België',
    dialingCode: '32',
    isoCode: 'BE',
    continent: Continent.EU,
    capital: 'Brussels',
    currency: 'EUR',
    languages: ["nl", "fr", "de"],
    emoji: '🇧🇪',
    emojiUnicode: 'U+1F1E7 U+1F1EA',
  );
  static const Country BF = Country(
    name: 'Burkina Faso',
    nativeName: 'Burkina Faso',
    dialingCode: '226',
    isoCode: 'BF',
    continent: Continent.AF,
    capital: 'Ouagadougou',
    currency: 'XOF',
    languages: ["fr", "ff"],
    emoji: '🇧🇫',
    emojiUnicode: 'U+1F1E7 U+1F1EB',
  );
  static const Country BG = Country(
    name: 'Bulgaria',
    nativeName: 'България',
    dialingCode: '359',
    isoCode: 'BG',
    continent: Continent.EU,
    capital: 'Sofia',
    currency: 'BGN',
    languages: ["bg"],
    emoji: '🇧🇬',
    emojiUnicode: 'U+1F1E7 U+1F1EC',
  );
  static const Country BH = Country(
    name: 'Bahrain',
    nativeName: '‏البحرين',
    dialingCode: '973',
    isoCode: 'BH',
    continent: Continent.AS,
    capital: 'Manama',
    currency: 'BHD',
    languages: ["ar"],
    emoji: '🇧🇭',
    emojiUnicode: 'U+1F1E7 U+1F1ED',
  );
  static const Country BI = Country(
    name: 'Burundi',
    nativeName: 'Burundi',
    dialingCode: '257',
    isoCode: 'BI',
    continent: Continent.AF,
    capital: 'Bujumbura',
    currency: 'BIF',
    languages: ["fr", "rn"],
    emoji: '🇧🇮',
    emojiUnicode: 'U+1F1E7 U+1F1EE',
  );
  static const Country BJ = Country(
    name: 'Benin',
    nativeName: 'Bénin',
    dialingCode: '229',
    isoCode: 'BJ',
    continent: Continent.AF,
    capital: 'Porto-Novo',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇧🇯',
    emojiUnicode: 'U+1F1E7 U+1F1EF',
  );
  static const Country BL = Country(
    name: 'Saint Barthélemy',
    nativeName: 'Saint-Barthélemy',
    dialingCode: '590',
    isoCode: 'BL',
    continent: Continent.NA,
    capital: 'Gustavia',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇧🇱',
    emojiUnicode: 'U+1F1E7 U+1F1F1',
  );
  static const Country BM = Country(
    name: 'Bermuda',
    nativeName: 'Bermuda',
    dialingCode: '1441',
    isoCode: 'BM',
    continent: Continent.NA,
    capital: 'Hamilton',
    currency: 'BMD',
    languages: ["en"],
    emoji: '🇧🇲',
    emojiUnicode: 'U+1F1E7 U+1F1F2',
  );
  static const Country BN = Country(
    name: 'Brunei',
    nativeName: 'Negara Brunei Darussalam',
    dialingCode: '673',
    isoCode: 'BN',
    continent: Continent.AS,
    capital: 'Bandar Seri Begawan',
    currency: 'BND',
    languages: ["ms"],
    emoji: '🇧🇳',
    emojiUnicode: 'U+1F1E7 U+1F1F3',
  );
  static const Country BO = Country(
    name: 'Bolivia',
    nativeName: 'Bolivia',
    dialingCode: '591',
    isoCode: 'BO',
    continent: Continent.SA,
    capital: 'Sucre',
    currency: 'BOB,BOV',
    languages: ["es", "ay", "qu"],
    emoji: '🇧🇴',
    emojiUnicode: 'U+1F1E7 U+1F1F4',
  );
  static const Country BQ = Country(
    name: 'Bonaire',
    nativeName: 'Bonaire',
    dialingCode: '5997',
    isoCode: 'BQ',
    continent: Continent.NA,
    capital: 'Kralendijk',
    currency: 'USD',
    languages: ["nl"],
    emoji: '🇧🇶',
    emojiUnicode: 'U+1F1E7 U+1F1F6',
  );
  static const Country BR = Country(
    name: 'Brazil',
    nativeName: 'Brasil',
    dialingCode: '55',
    isoCode: 'BR',
    continent: Continent.SA,
    capital: 'Brasília',
    currency: 'BRL',
    languages: ["pt"],
    emoji: '🇧🇷',
    emojiUnicode: 'U+1F1E7 U+1F1F7',
  );
  static const Country BS = Country(
    name: 'Bahamas',
    nativeName: 'Bahamas',
    dialingCode: '1242',
    isoCode: 'BS',
    continent: Continent.NA,
    capital: 'Nassau',
    currency: 'BSD',
    languages: ["en"],
    emoji: '🇧🇸',
    emojiUnicode: 'U+1F1E7 U+1F1F8',
  );
  static const Country BT = Country(
    name: 'Bhutan',
    nativeName: 'ʼbrug-yul',
    dialingCode: '975',
    isoCode: 'BT',
    continent: Continent.AS,
    capital: 'Thimphu',
    currency: 'BTN,INR',
    languages: ["dz"],
    emoji: '🇧🇹',
    emojiUnicode: 'U+1F1E7 U+1F1F9',
  );
  static const Country BV = Country(
    name: 'Bouvet Island',
    nativeName: 'Bouvetøya',
    dialingCode: '47',
    isoCode: 'BV',
    continent: Continent.AN,
    capital: '',
    currency: 'NOK',
    languages: ["no", "nb", "nn"],
    emoji: '🇧🇻',
    emojiUnicode: 'U+1F1E7 U+1F1FB',
  );
  static const Country BW = Country(
    name: 'Botswana',
    nativeName: 'Botswana',
    dialingCode: '267',
    isoCode: 'BW',
    continent: Continent.AF,
    capital: 'Gaborone',
    currency: 'BWP',
    languages: ["en", "tn"],
    emoji: '🇧🇼',
    emojiUnicode: 'U+1F1E7 U+1F1FC',
  );
  static const Country BY = Country(
    name: 'Belarus',
    nativeName: 'Белару́сь',
    dialingCode: '375',
    isoCode: 'BY',
    continent: Continent.EU,
    capital: 'Minsk',
    currency: 'BYR',
    languages: ["be", "ru"],
    emoji: '🇧🇾',
    emojiUnicode: 'U+1F1E7 U+1F1FE',
  );
  static const Country BZ = Country(
    name: 'Belize',
    nativeName: 'Belize',
    dialingCode: '501',
    isoCode: 'BZ',
    continent: Continent.NA,
    capital: 'Belmopan',
    currency: 'BZD',
    languages: ["en", "es"],
    emoji: '🇧🇿',
    emojiUnicode: 'U+1F1E7 U+1F1FF',
  );
  static const Country CA = Country(
    name: 'Canada',
    nativeName: 'Canada',
    dialingCode: '1',
    isoCode: 'CA',
    continent: Continent.NA,
    capital: 'Ottawa',
    currency: 'CAD',
    languages: ["en", "fr"],
    emoji: '🇨🇦',
    emojiUnicode: 'U+1F1E8 U+1F1E6',
  );
  static const Country CC = Country(
    name: 'Cocos [Keeling] Islands',
    nativeName: 'Cocos (Keeling) Islands',
    dialingCode: '61',
    isoCode: 'CC',
    continent: Continent.AS,
    capital: 'West Island',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇨🇨',
    emojiUnicode: 'U+1F1E8 U+1F1E8',
  );
  static const Country CD = Country(
    name: 'Democratic Republic of the Congo',
    nativeName: 'République démocratique du Congo',
    dialingCode: '243',
    isoCode: 'CD',
    continent: Continent.AF,
    capital: 'Kinshasa',
    currency: 'CDF',
    languages: ["fr", "ln", "kg", "sw", "lu"],
    emoji: '🇨🇩',
    emojiUnicode: 'U+1F1E8 U+1F1E9',
  );
  static const Country CF = Country(
    name: 'Central African Republic',
    nativeName: 'Ködörösêse tî Bêafrîka',
    dialingCode: '236',
    isoCode: 'CF',
    continent: Continent.AF,
    capital: 'Bangui',
    currency: 'XAF',
    languages: ["fr", "sg"],
    emoji: '🇨🇫',
    emojiUnicode: 'U+1F1E8 U+1F1EB',
  );
  static const Country CG = Country(
    name: 'Republic of the Congo',
    nativeName: 'République du Congo',
    dialingCode: '242',
    isoCode: 'CG',
    continent: Continent.AF,
    capital: 'Brazzaville',
    currency: 'XAF',
    languages: ["fr", "ln"],
    emoji: '🇨🇬',
    emojiUnicode: 'U+1F1E8 U+1F1EC',
  );
  static const Country CH = Country(
    name: 'Switzerland',
    nativeName: 'Schweiz',
    dialingCode: '41',
    isoCode: 'CH',
    continent: Continent.EU,
    capital: 'Bern',
    currency: 'CHE,CHF,CHW',
    languages: ["de", "fr", "it"],
    emoji: '🇨🇭',
    emojiUnicode: 'U+1F1E8 U+1F1ED',
  );
  static const Country CI = Country(
    name: 'Ivory Coast',
    nativeName: 'Côte d\'Ivoire',
    dialingCode: '225',
    isoCode: 'CI',
    continent: Continent.AF,
    capital: 'Yamoussoukro',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇨🇮',
    emojiUnicode: 'U+1F1E8 U+1F1EE',
  );
  static const Country CK = Country(
    name: 'Cook Islands',
    nativeName: 'Cook Islands',
    dialingCode: '682',
    isoCode: 'CK',
    continent: Continent.OC,
    capital: 'Avarua',
    currency: 'NZD',
    languages: ["en"],
    emoji: '🇨🇰',
    emojiUnicode: 'U+1F1E8 U+1F1F0',
  );
  static const Country CL = Country(
    name: 'Chile',
    nativeName: 'Chile',
    dialingCode: '56',
    isoCode: 'CL',
    continent: Continent.SA,
    capital: 'Santiago',
    currency: 'CLF,CLP',
    languages: ["es"],
    emoji: '🇨🇱',
    emojiUnicode: 'U+1F1E8 U+1F1F1',
  );
  static const Country CM = Country(
    name: 'Cameroon',
    nativeName: 'Cameroon',
    dialingCode: '237',
    isoCode: 'CM',
    continent: Continent.AF,
    capital: 'Yaoundé',
    currency: 'XAF',
    languages: ["en", "fr"],
    emoji: '🇨🇲',
    emojiUnicode: 'U+1F1E8 U+1F1F2',
  );
  static const Country CN = Country(
    name: 'China',
    nativeName: '中国',
    dialingCode: '86',
    isoCode: 'CN',
    continent: Continent.AS,
    capital: 'Beijing',
    currency: 'CNY',
    languages: ["zh"],
    emoji: '🇨🇳',
    emojiUnicode: 'U+1F1E8 U+1F1F3',
  );
  static const Country CO = Country(
    name: 'Colombia',
    nativeName: 'Colombia',
    dialingCode: '57',
    isoCode: 'CO',
    continent: Continent.SA,
    capital: 'Bogotá',
    currency: 'COP',
    languages: ["es"],
    emoji: '🇨🇴',
    emojiUnicode: 'U+1F1E8 U+1F1F4',
  );
  static const Country CR = Country(
    name: 'Costa Rica',
    nativeName: 'Costa Rica',
    dialingCode: '506',
    isoCode: 'CR',
    continent: Continent.NA,
    capital: 'San José',
    currency: 'CRC',
    languages: ["es"],
    emoji: '🇨🇷',
    emojiUnicode: 'U+1F1E8 U+1F1F7',
  );
  static const Country CU = Country(
    name: 'Cuba',
    nativeName: 'Cuba',
    dialingCode: '53',
    isoCode: 'CU',
    continent: Continent.NA,
    capital: 'Havana',
    currency: 'CUC,CUP',
    languages: ["es"],
    emoji: '🇨🇺',
    emojiUnicode: 'U+1F1E8 U+1F1FA',
  );
  static const Country CV = Country(
    name: 'Cape Verde',
    nativeName: 'Cabo Verde',
    dialingCode: '238',
    isoCode: 'CV',
    continent: Continent.AF,
    capital: 'Praia',
    currency: 'CVE',
    languages: ["pt"],
    emoji: '🇨🇻',
    emojiUnicode: 'U+1F1E8 U+1F1FB',
  );
  static const Country CW = Country(
    name: 'Curacao',
    nativeName: 'Curaçao',
    dialingCode: '5999',
    isoCode: 'CW',
    continent: Continent.NA,
    capital: 'Willemstad',
    currency: 'ANG',
    languages: ["nl", "pa", "en"],
    emoji: '🇨🇼',
    emojiUnicode: 'U+1F1E8 U+1F1FC',
  );
  static const Country CX = Country(
    name: 'Christmas Island',
    nativeName: 'Christmas Island',
    dialingCode: '61',
    isoCode: 'CX',
    continent: Continent.AS,
    capital: 'Flying Fish Cove',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇨🇽',
    emojiUnicode: 'U+1F1E8 U+1F1FD',
  );
  static const Country CY = Country(
    name: 'Cyprus',
    nativeName: 'Κύπρος',
    dialingCode: '357',
    isoCode: 'CY',
    continent: Continent.EU,
    capital: 'Nicosia',
    currency: 'EUR',
    languages: ["el", "tr", "hy"],
    emoji: '🇨🇾',
    emojiUnicode: 'U+1F1E8 U+1F1FE',
  );
  static const Country CZ = Country(
    name: 'Czech Republic',
    nativeName: 'Česká republika',
    dialingCode: '420',
    isoCode: 'CZ',
    continent: Continent.EU,
    capital: 'Prague',
    currency: 'CZK',
    languages: ["cs", "sk"],
    emoji: '🇨🇿',
    emojiUnicode: 'U+1F1E8 U+1F1FF',
  );
  static const Country DE = Country(
    name: 'Germany',
    nativeName: 'Deutschland',
    dialingCode: '49',
    isoCode: 'DE',
    continent: Continent.EU,
    capital: 'Berlin',
    currency: 'EUR',
    languages: ["de"],
    emoji: '🇩🇪',
    emojiUnicode: 'U+1F1E9 U+1F1EA',
  );
  static const Country DJ = Country(
    name: 'Djibouti',
    nativeName: 'Djibouti',
    dialingCode: '253',
    isoCode: 'DJ',
    continent: Continent.AF,
    capital: 'Djibouti',
    currency: 'DJF',
    languages: ["fr", "ar"],
    emoji: '🇩🇯',
    emojiUnicode: 'U+1F1E9 U+1F1EF',
  );
  static const Country DK = Country(
    name: 'Denmark',
    nativeName: 'Danmark',
    dialingCode: '45',
    isoCode: 'DK',
    continent: Continent.EU,
    capital: 'Copenhagen',
    currency: 'DKK',
    languages: ["da"],
    emoji: '🇩🇰',
    emojiUnicode: 'U+1F1E9 U+1F1F0',
  );
  static const Country DM = Country(
    name: 'Dominica',
    nativeName: 'Dominica',
    dialingCode: '1767',
    isoCode: 'DM',
    continent: Continent.NA,
    capital: 'Roseau',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇩🇲',
    emojiUnicode: 'U+1F1E9 U+1F1F2',
  );
  static const Country DO = Country(
    name: 'Dominican Republic',
    nativeName: 'República Dominicana',
    dialingCode: '1809,1829,1849',
    isoCode: 'DO',
    continent: Continent.NA,
    capital: 'Santo Domingo',
    currency: 'DOP',
    languages: ["es"],
    emoji: '🇩🇴',
    emojiUnicode: 'U+1F1E9 U+1F1F4',
  );
  static const Country DZ = Country(
    name: 'Algeria',
    nativeName: 'الجزائر',
    dialingCode: '213',
    isoCode: 'DZ',
    continent: Continent.AF,
    capital: 'Algiers',
    currency: 'DZD',
    languages: ["ar"],
    emoji: '🇩🇿',
    emojiUnicode: 'U+1F1E9 U+1F1FF',
  );
  static const Country EC = Country(
    name: 'Ecuador',
    nativeName: 'Ecuador',
    dialingCode: '593',
    isoCode: 'EC',
    continent: Continent.SA,
    capital: 'Quito',
    currency: 'USD',
    languages: ["es"],
    emoji: '🇪🇨',
    emojiUnicode: 'U+1F1EA U+1F1E8',
  );
  static const Country EE = Country(
    name: 'Estonia',
    nativeName: 'Eesti',
    dialingCode: '372',
    isoCode: 'EE',
    continent: Continent.EU,
    capital: 'Tallinn',
    currency: 'EUR',
    languages: ["et"],
    emoji: '🇪🇪',
    emojiUnicode: 'U+1F1EA U+1F1EA',
  );
  static const Country EG = Country(
    name: 'Egypt',
    nativeName: 'مصر‎',
    dialingCode: '20',
    isoCode: 'EG',
    continent: Continent.AF,
    capital: 'Cairo',
    currency: 'EGP',
    languages: ["ar"],
    emoji: '🇪🇬',
    emojiUnicode: 'U+1F1EA U+1F1EC',
  );
  static const Country EH = Country(
    name: 'Western Sahara',
    nativeName: 'الصحراء الغربية',
    dialingCode: '212',
    isoCode: 'EH',
    continent: Continent.AF,
    capital: 'El Aaiún',
    currency: 'MAD,DZD,MRU',
    languages: ["es"],
    emoji: '🇪🇭',
    emojiUnicode: 'U+1F1EA U+1F1ED',
  );
  static const Country ER = Country(
    name: 'Eritrea',
    nativeName: 'ኤርትራ',
    dialingCode: '291',
    isoCode: 'ER',
    continent: Continent.AF,
    capital: 'Asmara',
    currency: 'ERN',
    languages: ["ti", "ar", "en"],
    emoji: '🇪🇷',
    emojiUnicode: 'U+1F1EA U+1F1F7',
  );
  static const Country ES = Country(
    name: 'Spain',
    nativeName: 'España',
    dialingCode: '34',
    isoCode: 'ES',
    continent: Continent.EU,
    capital: 'Madrid',
    currency: 'EUR',
    languages: ["es", "eu", "ca", "gl", "oc"],
    emoji: '🇪🇸',
    emojiUnicode: 'U+1F1EA U+1F1F8',
  );
  static const Country ET = Country(
    name: 'Ethiopia',
    nativeName: 'ኢትዮጵያ',
    dialingCode: '251',
    isoCode: 'ET',
    continent: Continent.AF,
    capital: 'Addis Ababa',
    currency: 'ETB',
    languages: ["am"],
    emoji: '🇪🇹',
    emojiUnicode: 'U+1F1EA U+1F1F9',
  );
  static const Country FI = Country(
    name: 'Finland',
    nativeName: 'Suomi',
    dialingCode: '358',
    isoCode: 'FI',
    continent: Continent.EU,
    capital: 'Helsinki',
    currency: 'EUR',
    languages: ["fi", "sv"],
    emoji: '🇫🇮',
    emojiUnicode: 'U+1F1EB U+1F1EE',
  );
  static const Country FJ = Country(
    name: 'Fiji',
    nativeName: 'Fiji',
    dialingCode: '679',
    isoCode: 'FJ',
    continent: Continent.OC,
    capital: 'Suva',
    currency: 'FJD',
    languages: ["en", "fj", "hi", "ur"],
    emoji: '🇫🇯',
    emojiUnicode: 'U+1F1EB U+1F1EF',
  );
  static const Country FK = Country(
    name: 'Falkland Islands',
    nativeName: 'Falkland Islands',
    dialingCode: '500',
    isoCode: 'FK',
    continent: Continent.SA,
    capital: 'Stanley',
    currency: 'FKP',
    languages: ["en"],
    emoji: '🇫🇰',
    emojiUnicode: 'U+1F1EB U+1F1F0',
  );
  static const Country FM = Country(
    name: 'Micronesia',
    nativeName: 'Micronesia',
    dialingCode: '691',
    isoCode: 'FM',
    continent: Continent.OC,
    capital: 'Palikir',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇫🇲',
    emojiUnicode: 'U+1F1EB U+1F1F2',
  );
  static const Country FO = Country(
    name: 'Faroe Islands',
    nativeName: 'Føroyar',
    dialingCode: '298',
    isoCode: 'FO',
    continent: Continent.EU,
    capital: 'Tórshavn',
    currency: 'DKK',
    languages: ["fo"],
    emoji: '🇫🇴',
    emojiUnicode: 'U+1F1EB U+1F1F4',
  );
  static const Country FR = Country(
    name: 'France',
    nativeName: 'France',
    dialingCode: '33',
    isoCode: 'FR',
    continent: Continent.EU,
    capital: 'Paris',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇫🇷',
    emojiUnicode: 'U+1F1EB U+1F1F7',
  );
  static const Country GA = Country(
    name: 'Gabon',
    nativeName: 'Gabon',
    dialingCode: '241',
    isoCode: 'GA',
    continent: Continent.AF,
    capital: 'Libreville',
    currency: 'XAF',
    languages: ["fr"],
    emoji: '🇬🇦',
    emojiUnicode: 'U+1F1EC U+1F1E6',
  );
  static const Country GB = Country(
    name: 'United Kingdom',
    nativeName: 'United Kingdom',
    dialingCode: '44',
    isoCode: 'GB',
    continent: Continent.EU,
    capital: 'London',
    currency: 'GBP',
    languages: ["en"],
    emoji: '🇬🇧',
    emojiUnicode: 'U+1F1EC U+1F1E7',
  );
  static const Country GD = Country(
    name: 'Grenada',
    nativeName: 'Grenada',
    dialingCode: '1473',
    isoCode: 'GD',
    continent: Continent.NA,
    capital: 'St. George\'s',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇬🇩',
    emojiUnicode: 'U+1F1EC U+1F1E9',
  );
  static const Country GE = Country(
    name: 'Georgia',
    nativeName: 'საქართველო',
    dialingCode: '995',
    isoCode: 'GE',
    continent: Continent.AS,
    capital: 'Tbilisi',
    currency: 'GEL',
    languages: ["ka"],
    emoji: '🇬🇪',
    emojiUnicode: 'U+1F1EC U+1F1EA',
  );
  static const Country GF = Country(
    name: 'French Guiana',
    nativeName: 'Guyane française',
    dialingCode: '594',
    isoCode: 'GF',
    continent: Continent.SA,
    capital: 'Cayenne',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇬🇫',
    emojiUnicode: 'U+1F1EC U+1F1EB',
  );
  static const Country GG = Country(
    name: 'Guernsey',
    nativeName: 'Guernsey',
    dialingCode: '44',
    isoCode: 'GG',
    continent: Continent.EU,
    capital: 'St. Peter Port',
    currency: 'GBP',
    languages: ["en", "fr"],
    emoji: '🇬🇬',
    emojiUnicode: 'U+1F1EC U+1F1EC',
  );
  static const Country GH = Country(
    name: 'Ghana',
    nativeName: 'Ghana',
    dialingCode: '233',
    isoCode: 'GH',
    continent: Continent.AF,
    capital: 'Accra',
    currency: 'GHS',
    languages: ["en"],
    emoji: '🇬🇭',
    emojiUnicode: 'U+1F1EC U+1F1ED',
  );
  static const Country GI = Country(
    name: 'Gibraltar',
    nativeName: 'Gibraltar',
    dialingCode: '350',
    isoCode: 'GI',
    continent: Continent.EU,
    capital: 'Gibraltar',
    currency: 'GIP',
    languages: ["en"],
    emoji: '🇬🇮',
    emojiUnicode: 'U+1F1EC U+1F1EE',
  );
  static const Country GL = Country(
    name: 'Greenland',
    nativeName: 'Kalaallit Nunaat',
    dialingCode: '299',
    isoCode: 'GL',
    continent: Continent.NA,
    capital: 'Nuuk',
    currency: 'DKK',
    languages: ["kl"],
    emoji: '🇬🇱',
    emojiUnicode: 'U+1F1EC U+1F1F1',
  );
  static const Country GM = Country(
    name: 'Gambia',
    nativeName: 'Gambia',
    dialingCode: '220',
    isoCode: 'GM',
    continent: Continent.AF,
    capital: 'Banjul',
    currency: 'GMD',
    languages: ["en"],
    emoji: '🇬🇲',
    emojiUnicode: 'U+1F1EC U+1F1F2',
  );
  static const Country GN = Country(
    name: 'Guinea',
    nativeName: 'Guinée',
    dialingCode: '224',
    isoCode: 'GN',
    continent: Continent.AF,
    capital: 'Conakry',
    currency: 'GNF',
    languages: ["fr", "ff"],
    emoji: '🇬🇳',
    emojiUnicode: 'U+1F1EC U+1F1F3',
  );
  static const Country GP = Country(
    name: 'Guadeloupe',
    nativeName: 'Guadeloupe',
    dialingCode: '590',
    isoCode: 'GP',
    continent: Continent.NA,
    capital: 'Basse-Terre',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇬🇵',
    emojiUnicode: 'U+1F1EC U+1F1F5',
  );
  static const Country GQ = Country(
    name: 'Equatorial Guinea',
    nativeName: 'Guinea Ecuatorial',
    dialingCode: '240',
    isoCode: 'GQ',
    continent: Continent.AF,
    capital: 'Malabo',
    currency: 'XAF',
    languages: ["es", "fr"],
    emoji: '🇬🇶',
    emojiUnicode: 'U+1F1EC U+1F1F6',
  );
  static const Country GR = Country(
    name: 'Greece',
    nativeName: 'Ελλάδα',
    dialingCode: '30',
    isoCode: 'GR',
    continent: Continent.EU,
    capital: 'Athens',
    currency: 'EUR',
    languages: ["el"],
    emoji: '🇬🇷',
    emojiUnicode: 'U+1F1EC U+1F1F7',
  );
  static const Country GS = Country(
    name: 'South Georgia and the South Sandwich Islands',
    nativeName: 'South Georgia',
    dialingCode: '500',
    isoCode: 'GS',
    continent: Continent.AN,
    capital: 'King Edward Point',
    currency: 'GBP',
    languages: ["en"],
    emoji: '🇬🇸',
    emojiUnicode: 'U+1F1EC U+1F1F8',
  );
  static const Country GT = Country(
    name: 'Guatemala',
    nativeName: 'Guatemala',
    dialingCode: '502',
    isoCode: 'GT',
    continent: Continent.NA,
    capital: 'Guatemala City',
    currency: 'GTQ',
    languages: ["es"],
    emoji: '🇬🇹',
    emojiUnicode: 'U+1F1EC U+1F1F9',
  );
  static const Country GU = Country(
    name: 'Guam',
    nativeName: 'Guam',
    dialingCode: '1671',
    isoCode: 'GU',
    continent: Continent.OC,
    capital: 'Hagåtña',
    currency: 'USD',
    languages: ["en", "ch", "es"],
    emoji: '🇬🇺',
    emojiUnicode: 'U+1F1EC U+1F1FA',
  );
  static const Country GW = Country(
    name: 'Guinea-Bissau',
    nativeName: 'Guiné-Bissau',
    dialingCode: '245',
    isoCode: 'GW',
    continent: Continent.AF,
    capital: 'Bissau',
    currency: 'XOF',
    languages: ["pt"],
    emoji: '🇬🇼',
    emojiUnicode: 'U+1F1EC U+1F1FC',
  );
  static const Country GY = Country(
    name: 'Guyana',
    nativeName: 'Guyana',
    dialingCode: '592',
    isoCode: 'GY',
    continent: Continent.SA,
    capital: 'Georgetown',
    currency: 'GYD',
    languages: ["en"],
    emoji: '🇬🇾',
    emojiUnicode: 'U+1F1EC U+1F1FE',
  );
  static const Country HK = Country(
    name: 'Hong Kong',
    nativeName: '香港',
    dialingCode: '852',
    isoCode: 'HK',
    continent: Continent.AS,
    capital: 'City of Victoria',
    currency: 'HKD',
    languages: ["zh", "en"],
    emoji: '🇭🇰',
    emojiUnicode: 'U+1F1ED U+1F1F0',
  );
  static const Country HM = Country(
    name: 'Heard Island and McDonald Islands',
    nativeName: 'Heard Island and McDonald Islands',
    dialingCode: '61',
    isoCode: 'HM',
    continent: Continent.AN,
    capital: '',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇭🇲',
    emojiUnicode: 'U+1F1ED U+1F1F2',
  );
  static const Country HN = Country(
    name: 'Honduras',
    nativeName: 'Honduras',
    dialingCode: '504',
    isoCode: 'HN',
    continent: Continent.NA,
    capital: 'Tegucigalpa',
    currency: 'HNL',
    languages: ["es"],
    emoji: '🇭🇳',
    emojiUnicode: 'U+1F1ED U+1F1F3',
  );
  static const Country HR = Country(
    name: 'Croatia',
    nativeName: 'Hrvatska',
    dialingCode: '385',
    isoCode: 'HR',
    continent: Continent.EU,
    capital: 'Zagreb',
    currency: 'HRK',
    languages: ["hr"],
    emoji: '🇭🇷',
    emojiUnicode: 'U+1F1ED U+1F1F7',
  );
  static const Country HT = Country(
    name: 'Haiti',
    nativeName: 'Haïti',
    dialingCode: '509',
    isoCode: 'HT',
    continent: Continent.NA,
    capital: 'Port-au-Prince',
    currency: 'HTG,USD',
    languages: ["fr", "ht"],
    emoji: '🇭🇹',
    emojiUnicode: 'U+1F1ED U+1F1F9',
  );
  static const Country HU = Country(
    name: 'Hungary',
    nativeName: 'Magyarország',
    dialingCode: '36',
    isoCode: 'HU',
    continent: Continent.EU,
    capital: 'Budapest',
    currency: 'HUF',
    languages: ["hu"],
    emoji: '🇭🇺',
    emojiUnicode: 'U+1F1ED U+1F1FA',
  );
  static const Country ID = Country(
    name: 'Indonesia',
    nativeName: 'Indonesia',
    dialingCode: '62',
    isoCode: 'ID',
    continent: Continent.AS,
    capital: 'Jakarta',
    currency: 'IDR',
    languages: ["id"],
    emoji: '🇮🇩',
    emojiUnicode: 'U+1F1EE U+1F1E9',
  );
  static const Country IE = Country(
    name: 'Ireland',
    nativeName: 'Éire',
    dialingCode: '353',
    isoCode: 'IE',
    continent: Continent.EU,
    capital: 'Dublin',
    currency: 'EUR',
    languages: ["ga", "en"],
    emoji: '🇮🇪',
    emojiUnicode: 'U+1F1EE U+1F1EA',
  );
  static const Country IL = Country(
    name: 'Israel',
    nativeName: 'יִשְׂרָאֵל',
    dialingCode: '972',
    isoCode: 'IL',
    continent: Continent.AS,
    capital: 'Jerusalem',
    currency: 'ILS',
    languages: ["he", "ar"],
    emoji: '🇮🇱',
    emojiUnicode: 'U+1F1EE U+1F1F1',
  );
  static const Country IM = Country(
    name: 'Isle of Man',
    nativeName: 'Isle of Man',
    dialingCode: '44',
    isoCode: 'IM',
    continent: Continent.EU,
    capital: 'Douglas',
    currency: 'GBP',
    languages: ["en", "gv"],
    emoji: '🇮🇲',
    emojiUnicode: 'U+1F1EE U+1F1F2',
  );
  static const Country IN = Country(
    name: 'India',
    nativeName: 'भारत',
    dialingCode: '91',
    isoCode: 'IN',
    continent: Continent.AS,
    capital: 'New Delhi',
    currency: 'INR',
    languages: ["hi", "en"],
    emoji: '🇮🇳',
    emojiUnicode: 'U+1F1EE U+1F1F3',
  );
  static const Country IO = Country(
    name: 'British Indian Ocean Territory',
    nativeName: 'British Indian Ocean Territory',
    dialingCode: '246',
    isoCode: 'IO',
    continent: Continent.AS,
    capital: 'Diego Garcia',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇮🇴',
    emojiUnicode: 'U+1F1EE U+1F1F4',
  );
  static const Country IQ = Country(
    name: 'Iraq',
    nativeName: 'العراق',
    dialingCode: '964',
    isoCode: 'IQ',
    continent: Continent.AS,
    capital: 'Baghdad',
    currency: 'IQD',
    languages: ["ar", "ku"],
    emoji: '🇮🇶',
    emojiUnicode: 'U+1F1EE U+1F1F6',
  );
  static const Country IR = Country(
    name: 'Iran',
    nativeName: 'ایران',
    dialingCode: '98',
    isoCode: 'IR',
    continent: Continent.AS,
    capital: 'Tehran',
    currency: 'IRR',
    languages: ["fa"],
    emoji: '🇮🇷',
    emojiUnicode: 'U+1F1EE U+1F1F7',
  );
  static const Country IS = Country(
    name: 'Iceland',
    nativeName: 'Ísland',
    dialingCode: '354',
    isoCode: 'IS',
    continent: Continent.EU,
    capital: 'Reykjavik',
    currency: 'ISK',
    languages: ["is"],
    emoji: '🇮🇸',
    emojiUnicode: 'U+1F1EE U+1F1F8',
  );
  static const Country IT = Country(
    name: 'Italy',
    nativeName: 'Italia',
    dialingCode: '39',
    isoCode: 'IT',
    continent: Continent.EU,
    capital: 'Rome',
    currency: 'EUR',
    languages: ["it"],
    emoji: '🇮🇹',
    emojiUnicode: 'U+1F1EE U+1F1F9',
  );
  static const Country JE = Country(
    name: 'Jersey',
    nativeName: 'Jersey',
    dialingCode: '44',
    isoCode: 'JE',
    continent: Continent.EU,
    capital: 'Saint Helier',
    currency: 'GBP',
    languages: ["en", "fr"],
    emoji: '🇯🇪',
    emojiUnicode: 'U+1F1EF U+1F1EA',
  );
  static const Country JM = Country(
    name: 'Jamaica',
    nativeName: 'Jamaica',
    dialingCode: '1876',
    isoCode: 'JM',
    continent: Continent.NA,
    capital: 'Kingston',
    currency: 'JMD',
    languages: ["en"],
    emoji: '🇯🇲',
    emojiUnicode: 'U+1F1EF U+1F1F2',
  );
  static const Country JO = Country(
    name: 'Jordan',
    nativeName: 'الأردن',
    dialingCode: '962',
    isoCode: 'JO',
    continent: Continent.AS,
    capital: 'Amman',
    currency: 'JOD',
    languages: ["ar"],
    emoji: '🇯🇴',
    emojiUnicode: 'U+1F1EF U+1F1F4',
  );
  static const Country JP = Country(
    name: 'Japan',
    nativeName: '日本',
    dialingCode: '81',
    isoCode: 'JP',
    continent: Continent.AS,
    capital: 'Tokyo',
    currency: 'JPY',
    languages: ["ja"],
    emoji: '🇯🇵',
    emojiUnicode: 'U+1F1EF U+1F1F5',
  );
  static const Country KE = Country(
    name: 'Kenya',
    nativeName: 'Kenya',
    dialingCode: '254',
    isoCode: 'KE',
    continent: Continent.AF,
    capital: 'Nairobi',
    currency: 'KES',
    languages: ["en", "sw"],
    emoji: '🇰🇪',
    emojiUnicode: 'U+1F1F0 U+1F1EA',
  );
  static const Country KG = Country(
    name: 'Kyrgyzstan',
    nativeName: 'Кыргызстан',
    dialingCode: '996',
    isoCode: 'KG',
    continent: Continent.AS,
    capital: 'Bishkek',
    currency: 'KGS',
    languages: ["ky", "ru"],
    emoji: '🇰🇬',
    emojiUnicode: 'U+1F1F0 U+1F1EC',
  );
  static const Country KH = Country(
    name: 'Cambodia',
    nativeName: 'Kâmpŭchéa',
    dialingCode: '855',
    isoCode: 'KH',
    continent: Continent.AS,
    capital: 'Phnom Penh',
    currency: 'KHR',
    languages: ["km"],
    emoji: '🇰🇭',
    emojiUnicode: 'U+1F1F0 U+1F1ED',
  );
  static const Country KI = Country(
    name: 'Kiribati',
    nativeName: 'Kiribati',
    dialingCode: '686',
    isoCode: 'KI',
    continent: Continent.OC,
    capital: 'South Tarawa',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇰🇮',
    emojiUnicode: 'U+1F1F0 U+1F1EE',
  );
  static const Country KM = Country(
    name: 'Comoros',
    nativeName: 'Komori',
    dialingCode: '269',
    isoCode: 'KM',
    continent: Continent.AF,
    capital: 'Moroni',
    currency: 'KMF',
    languages: ["ar", "fr"],
    emoji: '🇰🇲',
    emojiUnicode: 'U+1F1F0 U+1F1F2',
  );
  static const Country KN = Country(
    name: 'Saint Kitts and Nevis',
    nativeName: 'Saint Kitts and Nevis',
    dialingCode: '1869',
    isoCode: 'KN',
    continent: Continent.NA,
    capital: 'Basseterre',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇰🇳',
    emojiUnicode: 'U+1F1F0 U+1F1F3',
  );
  static const Country KP = Country(
    name: 'North Korea',
    nativeName: '북한',
    dialingCode: '850',
    isoCode: 'KP',
    continent: Continent.AS,
    capital: 'Pyongyang',
    currency: 'KPW',
    languages: ["ko"],
    emoji: '🇰🇵',
    emojiUnicode: 'U+1F1F0 U+1F1F5',
  );
  static const Country KR = Country(
    name: 'South Korea',
    nativeName: '대한민국',
    dialingCode: '82',
    isoCode: 'KR',
    continent: Continent.AS,
    capital: 'Seoul',
    currency: 'KRW',
    languages: ["ko"],
    emoji: '🇰🇷',
    emojiUnicode: 'U+1F1F0 U+1F1F7',
  );
  static const Country KW = Country(
    name: 'Kuwait',
    nativeName: 'الكويت',
    dialingCode: '965',
    isoCode: 'KW',
    continent: Continent.AS,
    capital: 'Kuwait City',
    currency: 'KWD',
    languages: ["ar"],
    emoji: '🇰🇼',
    emojiUnicode: 'U+1F1F0 U+1F1FC',
  );
  static const Country KY = Country(
    name: 'Cayman Islands',
    nativeName: 'Cayman Islands',
    dialingCode: '1345',
    isoCode: 'KY',
    continent: Continent.NA,
    capital: 'George Town',
    currency: 'KYD',
    languages: ["en"],
    emoji: '🇰🇾',
    emojiUnicode: 'U+1F1F0 U+1F1FE',
  );
  static const Country KZ = Country(
    name: 'Kazakhstan',
    nativeName: 'Қазақстан',
    dialingCode: '76,77',
    isoCode: 'KZ',
    continent: Continent.AS,
    capital: 'Astana',
    currency: 'KZT',
    languages: ["kk", "ru"],
    emoji: '🇰🇿',
    emojiUnicode: 'U+1F1F0 U+1F1FF',
  );
  static const Country LA = Country(
    name: 'Laos',
    nativeName: 'ສປປລາວ',
    dialingCode: '856',
    isoCode: 'LA',
    continent: Continent.AS,
    capital: 'Vientiane',
    currency: 'LAK',
    languages: ["lo"],
    emoji: '🇱🇦',
    emojiUnicode: 'U+1F1F1 U+1F1E6',
  );
  static const Country LB = Country(
    name: 'Lebanon',
    nativeName: 'لبنان',
    dialingCode: '961',
    isoCode: 'LB',
    continent: Continent.AS,
    capital: 'Beirut',
    currency: 'LBP',
    languages: ["ar", "fr"],
    emoji: '🇱🇧',
    emojiUnicode: 'U+1F1F1 U+1F1E7',
  );
  static const Country LC = Country(
    name: 'Saint Lucia',
    nativeName: 'Saint Lucia',
    dialingCode: '1758',
    isoCode: 'LC',
    continent: Continent.NA,
    capital: 'Castries',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇱🇨',
    emojiUnicode: 'U+1F1F1 U+1F1E8',
  );
  static const Country LI = Country(
    name: 'Liechtenstein',
    nativeName: 'Liechtenstein',
    dialingCode: '423',
    isoCode: 'LI',
    continent: Continent.EU,
    capital: 'Vaduz',
    currency: 'CHF',
    languages: ["de"],
    emoji: '🇱🇮',
    emojiUnicode: 'U+1F1F1 U+1F1EE',
  );
  static const Country LK = Country(
    name: 'Sri Lanka',
    nativeName: 'śrī laṃkāva',
    dialingCode: '94',
    isoCode: 'LK',
    continent: Continent.AS,
    capital: 'Colombo',
    currency: 'LKR',
    languages: ["si", "ta"],
    emoji: '🇱🇰',
    emojiUnicode: 'U+1F1F1 U+1F1F0',
  );
  static const Country LR = Country(
    name: 'Liberia',
    nativeName: 'Liberia',
    dialingCode: '231',
    isoCode: 'LR',
    continent: Continent.AF,
    capital: 'Monrovia',
    currency: 'LRD',
    languages: ["en"],
    emoji: '🇱🇷',
    emojiUnicode: 'U+1F1F1 U+1F1F7',
  );
  static const Country LS = Country(
    name: 'Lesotho',
    nativeName: 'Lesotho',
    dialingCode: '266',
    isoCode: 'LS',
    continent: Continent.AF,
    capital: 'Maseru',
    currency: 'LSL,ZAR',
    languages: ["en", "st"],
    emoji: '🇱🇸',
    emojiUnicode: 'U+1F1F1 U+1F1F8',
  );
  static const Country LT = Country(
    name: 'Lithuania',
    nativeName: 'Lietuva',
    dialingCode: '370',
    isoCode: 'LT',
    continent: Continent.EU,
    capital: 'Vilnius',
    currency: 'EUR',
    languages: ["lt"],
    emoji: '🇱🇹',
    emojiUnicode: 'U+1F1F1 U+1F1F9',
  );
  static const Country LU = Country(
    name: 'Luxembourg',
    nativeName: 'Luxembourg',
    dialingCode: '352',
    isoCode: 'LU',
    continent: Continent.EU,
    capital: 'Luxembourg',
    currency: 'EUR',
    languages: ["fr", "de", "lb"],
    emoji: '🇱🇺',
    emojiUnicode: 'U+1F1F1 U+1F1FA',
  );
  static const Country LV = Country(
    name: 'Latvia',
    nativeName: 'Latvija',
    dialingCode: '371',
    isoCode: 'LV',
    continent: Continent.EU,
    capital: 'Riga',
    currency: 'EUR',
    languages: ["lv"],
    emoji: '🇱🇻',
    emojiUnicode: 'U+1F1F1 U+1F1FB',
  );
  static const Country LY = Country(
    name: 'Libya',
    nativeName: '‏ليبيا',
    dialingCode: '218',
    isoCode: 'LY',
    continent: Continent.AF,
    capital: 'Tripoli',
    currency: 'LYD',
    languages: ["ar"],
    emoji: '🇱🇾',
    emojiUnicode: 'U+1F1F1 U+1F1FE',
  );
  static const Country MA = Country(
    name: 'Morocco',
    nativeName: 'المغرب',
    dialingCode: '212',
    isoCode: 'MA',
    continent: Continent.AF,
    capital: 'Rabat',
    currency: 'MAD',
    languages: ["ar"],
    emoji: '🇲🇦',
    emojiUnicode: 'U+1F1F2 U+1F1E6',
  );
  static const Country MC = Country(
    name: 'Monaco',
    nativeName: 'Monaco',
    dialingCode: '377',
    isoCode: 'MC',
    continent: Continent.EU,
    capital: 'Monaco',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇲🇨',
    emojiUnicode: 'U+1F1F2 U+1F1E8',
  );
  static const Country MD = Country(
    name: 'Moldova',
    nativeName: 'Moldova',
    dialingCode: '373',
    isoCode: 'MD',
    continent: Continent.EU,
    capital: 'Chișinău',
    currency: 'MDL',
    languages: ["ro"],
    emoji: '🇲🇩',
    emojiUnicode: 'U+1F1F2 U+1F1E9',
  );
  static const Country ME = Country(
    name: 'Montenegro',
    nativeName: 'Црна Гора',
    dialingCode: '382',
    isoCode: 'ME',
    continent: Continent.EU,
    capital: 'Podgorica',
    currency: 'EUR',
    languages: ["sr", "bs", "sq", "hr"],
    emoji: '🇲🇪',
    emojiUnicode: 'U+1F1F2 U+1F1EA',
  );
  static const Country MF = Country(
    name: 'Saint Martin',
    nativeName: 'Saint-Martin',
    dialingCode: '590',
    isoCode: 'MF',
    continent: Continent.NA,
    capital: 'Marigot',
    currency: 'EUR',
    languages: ["en", "fr", "nl"],
    emoji: '🇲🇫',
    emojiUnicode: 'U+1F1F2 U+1F1EB',
  );
  static const Country MG = Country(
    name: 'Madagascar',
    nativeName: 'Madagasikara',
    dialingCode: '261',
    isoCode: 'MG',
    continent: Continent.AF,
    capital: 'Antananarivo',
    currency: 'MGA',
    languages: ["fr", "mg"],
    emoji: '🇲🇬',
    emojiUnicode: 'U+1F1F2 U+1F1EC',
  );
  static const Country MH = Country(
    name: 'Marshall Islands',
    nativeName: 'M̧ajeļ',
    dialingCode: '692',
    isoCode: 'MH',
    continent: Continent.OC,
    capital: 'Majuro',
    currency: 'USD',
    languages: ["en", "mh"],
    emoji: '🇲🇭',
    emojiUnicode: 'U+1F1F2 U+1F1ED',
  );
  static const Country MK = Country(
    name: 'Macedonia',
    nativeName: 'Македонија',
    dialingCode: '389',
    isoCode: 'MK',
    continent: Continent.EU,
    capital: 'Skopje',
    currency: 'MKD',
    languages: ["mk"],
    emoji: '🇲🇰',
    emojiUnicode: 'U+1F1F2 U+1F1F0',
  );
  static const Country ML = Country(
    name: 'Mali',
    nativeName: 'Mali',
    dialingCode: '223',
    isoCode: 'ML',
    continent: Continent.AF,
    capital: 'Bamako',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇲🇱',
    emojiUnicode: 'U+1F1F2 U+1F1F1',
  );
  static const Country MM = Country(
    name: 'Myanmar [Burma]',
    nativeName: 'မြန်မာ',
    dialingCode: '95',
    isoCode: 'MM',
    continent: Continent.AS,
    capital: 'Naypyidaw',
    currency: 'MMK',
    languages: ["my"],
    emoji: '🇲🇲',
    emojiUnicode: 'U+1F1F2 U+1F1F2',
  );
  static const Country MN = Country(
    name: 'Mongolia',
    nativeName: 'Монгол улс',
    dialingCode: '976',
    isoCode: 'MN',
    continent: Continent.AS,
    capital: 'Ulan Bator',
    currency: 'MNT',
    languages: ["mn"],
    emoji: '🇲🇳',
    emojiUnicode: 'U+1F1F2 U+1F1F3',
  );
  static const Country MO = Country(
    name: 'Macao',
    nativeName: '澳門',
    dialingCode: '853',
    isoCode: 'MO',
    continent: Continent.AS,
    capital: '',
    currency: 'MOP',
    languages: ["zh", "pt"],
    emoji: '🇲🇴',
    emojiUnicode: 'U+1F1F2 U+1F1F4',
  );
  static const Country MP = Country(
    name: 'Northern Mariana Islands',
    nativeName: 'Northern Mariana Islands',
    dialingCode: '1670',
    isoCode: 'MP',
    continent: Continent.OC,
    capital: 'Saipan',
    currency: 'USD',
    languages: ["en", "ch"],
    emoji: '🇲🇵',
    emojiUnicode: 'U+1F1F2 U+1F1F5',
  );
  static const Country MQ = Country(
    name: 'Martinique',
    nativeName: 'Martinique',
    dialingCode: '596',
    isoCode: 'MQ',
    continent: Continent.NA,
    capital: 'Fort-de-France',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇲🇶',
    emojiUnicode: 'U+1F1F2 U+1F1F6',
  );
  static const Country MR = Country(
    name: 'Mauritania',
    nativeName: 'موريتانيا',
    dialingCode: '222',
    isoCode: 'MR',
    continent: Continent.AF,
    capital: 'Nouakchott',
    currency: 'MRU',
    languages: ["ar"],
    emoji: '🇲🇷',
    emojiUnicode: 'U+1F1F2 U+1F1F7',
  );
  static const Country MS = Country(
    name: 'Montserrat',
    nativeName: 'Montserrat',
    dialingCode: '1664',
    isoCode: 'MS',
    continent: Continent.NA,
    capital: 'Plymouth',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇲🇸',
    emojiUnicode: 'U+1F1F2 U+1F1F8',
  );
  static const Country MT = Country(
    name: 'Malta',
    nativeName: 'Malta',
    dialingCode: '356',
    isoCode: 'MT',
    continent: Continent.EU,
    capital: 'Valletta',
    currency: 'EUR',
    languages: ["mt", "en"],
    emoji: '🇲🇹',
    emojiUnicode: 'U+1F1F2 U+1F1F9',
  );
  static const Country MU = Country(
    name: 'Mauritius',
    nativeName: 'Maurice',
    dialingCode: '230',
    isoCode: 'MU',
    continent: Continent.AF,
    capital: 'Port Louis',
    currency: 'MUR',
    languages: ["en"],
    emoji: '🇲🇺',
    emojiUnicode: 'U+1F1F2 U+1F1FA',
  );
  static const Country MV = Country(
    name: 'Maldives',
    nativeName: 'Maldives',
    dialingCode: '960',
    isoCode: 'MV',
    continent: Continent.AS,
    capital: 'Malé',
    currency: 'MVR',
    languages: ["dv"],
    emoji: '🇲🇻',
    emojiUnicode: 'U+1F1F2 U+1F1FB',
  );
  static const Country MW = Country(
    name: 'Malawi',
    nativeName: 'Malawi',
    dialingCode: '265',
    isoCode: 'MW',
    continent: Continent.AF,
    capital: 'Lilongwe',
    currency: 'MWK',
    languages: ["en", "ny"],
    emoji: '🇲🇼',
    emojiUnicode: 'U+1F1F2 U+1F1FC',
  );
  static const Country MX = Country(
    name: 'Mexico',
    nativeName: 'México',
    dialingCode: '52',
    isoCode: 'MX',
    continent: Continent.NA,
    capital: 'Mexico City',
    currency: 'MXN',
    languages: ["es"],
    emoji: '🇲🇽',
    emojiUnicode: 'U+1F1F2 U+1F1FD',
  );
  static const Country MY = Country(
    name: 'Malaysia',
    nativeName: 'Malaysia',
    dialingCode: '60',
    isoCode: 'MY',
    continent: Continent.AS,
    capital: 'Kuala Lumpur',
    currency: 'MYR',
    languages: ["ms"],
    emoji: '🇲🇾',
    emojiUnicode: 'U+1F1F2 U+1F1FE',
  );
  static const Country MZ = Country(
    name: 'Mozambique',
    nativeName: 'Moçambique',
    dialingCode: '258',
    isoCode: 'MZ',
    continent: Continent.AF,
    capital: 'Maputo',
    currency: 'MZN',
    languages: ["pt"],
    emoji: '🇲🇿',
    emojiUnicode: 'U+1F1F2 U+1F1FF',
  );
  static const Country NA = Country(
    name: 'Namibia',
    nativeName: 'Namibia',
    dialingCode: '264',
    isoCode: 'NA',
    continent: Continent.AF,
    capital: 'Windhoek',
    currency: 'NAD,ZAR',
    languages: ["en", "af"],
    emoji: '🇳🇦',
    emojiUnicode: 'U+1F1F3 U+1F1E6',
  );
  static const Country NC = Country(
    name: 'New Caledonia',
    nativeName: 'Nouvelle-Calédonie',
    dialingCode: '687',
    isoCode: 'NC',
    continent: Continent.OC,
    capital: 'Nouméa',
    currency: 'XPF',
    languages: ["fr"],
    emoji: '🇳🇨',
    emojiUnicode: 'U+1F1F3 U+1F1E8',
  );
  static const Country NE = Country(
    name: 'Niger',
    nativeName: 'Niger',
    dialingCode: '227',
    isoCode: 'NE',
    continent: Continent.AF,
    capital: 'Niamey',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇳🇪',
    emojiUnicode: 'U+1F1F3 U+1F1EA',
  );
  static const Country NF = Country(
    name: 'Norfolk Island',
    nativeName: 'Norfolk Island',
    dialingCode: '672',
    isoCode: 'NF',
    continent: Continent.OC,
    capital: 'Kingston',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇳🇫',
    emojiUnicode: 'U+1F1F3 U+1F1EB',
  );
  static const Country NG = Country(
    name: 'Nigeria',
    nativeName: 'Nigeria',
    dialingCode: '234',
    isoCode: 'NG',
    continent: Continent.AF,
    capital: 'Abuja',
    currency: 'NGN',
    languages: ["en"],
    emoji: '🇳🇬',
    emojiUnicode: 'U+1F1F3 U+1F1EC',
  );
  static const Country NI = Country(
    name: 'Nicaragua',
    nativeName: 'Nicaragua',
    dialingCode: '505',
    isoCode: 'NI',
    continent: Continent.NA,
    capital: 'Managua',
    currency: 'NIO',
    languages: ["es"],
    emoji: '🇳🇮',
    emojiUnicode: 'U+1F1F3 U+1F1EE',
  );
  static const Country NL = Country(
    name: 'Netherlands',
    nativeName: 'Nederland',
    dialingCode: '31',
    isoCode: 'NL',
    continent: Continent.EU,
    capital: 'Amsterdam',
    currency: 'EUR',
    languages: ["nl"],
    emoji: '🇳🇱',
    emojiUnicode: 'U+1F1F3 U+1F1F1',
  );
  static const Country NO = Country(
    name: 'Norway',
    nativeName: 'Norge',
    dialingCode: '47',
    isoCode: 'NO',
    continent: Continent.EU,
    capital: 'Oslo',
    currency: 'NOK',
    languages: ["no", "nb", "nn"],
    emoji: '🇳🇴',
    emojiUnicode: 'U+1F1F3 U+1F1F4',
  );
  static const Country NP = Country(
    name: 'Nepal',
    nativeName: 'नपल',
    dialingCode: '977',
    isoCode: 'NP',
    continent: Continent.AS,
    capital: 'Kathmandu',
    currency: 'NPR',
    languages: ["ne"],
    emoji: '🇳🇵',
    emojiUnicode: 'U+1F1F3 U+1F1F5',
  );
  static const Country NR = Country(
    name: 'Nauru',
    nativeName: 'Nauru',
    dialingCode: '674',
    isoCode: 'NR',
    continent: Continent.OC,
    capital: 'Yaren',
    currency: 'AUD',
    languages: ["en", "na"],
    emoji: '🇳🇷',
    emojiUnicode: 'U+1F1F3 U+1F1F7',
  );
  static const Country NU = Country(
    name: 'Niue',
    nativeName: 'Niuē',
    dialingCode: '683',
    isoCode: 'NU',
    continent: Continent.OC,
    capital: 'Alofi',
    currency: 'NZD',
    languages: ["en"],
    emoji: '🇳🇺',
    emojiUnicode: 'U+1F1F3 U+1F1FA',
  );
  static const Country NZ = Country(
    name: 'New Zealand',
    nativeName: 'New Zealand',
    dialingCode: '64',
    isoCode: 'NZ',
    continent: Continent.OC,
    capital: 'Wellington',
    currency: 'NZD',
    languages: ["en", "mi"],
    emoji: '🇳🇿',
    emojiUnicode: 'U+1F1F3 U+1F1FF',
  );
  static const Country OM = Country(
    name: 'Oman',
    nativeName: 'عمان',
    dialingCode: '968',
    isoCode: 'OM',
    continent: Continent.AS,
    capital: 'Muscat',
    currency: 'OMR',
    languages: ["ar"],
    emoji: '🇴🇲',
    emojiUnicode: 'U+1F1F4 U+1F1F2',
  );
  static const Country PA = Country(
    name: 'Panama',
    nativeName: 'Panamá',
    dialingCode: '507',
    isoCode: 'PA',
    continent: Continent.NA,
    capital: 'Panama City',
    currency: 'PAB,USD',
    languages: ["es"],
    emoji: '🇵🇦',
    emojiUnicode: 'U+1F1F5 U+1F1E6',
  );
  static const Country PE = Country(
    name: 'Peru',
    nativeName: 'Perú',
    dialingCode: '51',
    isoCode: 'PE',
    continent: Continent.SA,
    capital: 'Lima',
    currency: 'PEN',
    languages: ["es"],
    emoji: '🇵🇪',
    emojiUnicode: 'U+1F1F5 U+1F1EA',
  );
  static const Country PF = Country(
    name: 'French Polynesia',
    nativeName: 'Polynésie française',
    dialingCode: '689',
    isoCode: 'PF',
    continent: Continent.OC,
    capital: 'Papeetē',
    currency: 'XPF',
    languages: ["fr"],
    emoji: '🇵🇫',
    emojiUnicode: 'U+1F1F5 U+1F1EB',
  );
  static const Country PG = Country(
    name: 'Papua New Guinea',
    nativeName: 'Papua Niugini',
    dialingCode: '675',
    isoCode: 'PG',
    continent: Continent.OC,
    capital: 'Port Moresby',
    currency: 'PGK',
    languages: ["en"],
    emoji: '🇵🇬',
    emojiUnicode: 'U+1F1F5 U+1F1EC',
  );
  static const Country PH = Country(
    name: 'Philippines',
    nativeName: 'Pilipinas',
    dialingCode: '63',
    isoCode: 'PH',
    continent: Continent.AS,
    capital: 'Manila',
    currency: 'PHP',
    languages: ["en"],
    emoji: '🇵🇭',
    emojiUnicode: 'U+1F1F5 U+1F1ED',
  );
  static const Country PK = Country(
    name: 'Pakistan',
    nativeName: 'Pakistan',
    dialingCode: '92',
    isoCode: 'PK',
    continent: Continent.AS,
    capital: 'Islamabad',
    currency: 'PKR',
    languages: ["en", "ur"],
    emoji: '🇵🇰',
    emojiUnicode: 'U+1F1F5 U+1F1F0',
  );
  static const Country PL = Country(
    name: 'Poland',
    nativeName: 'Polska',
    dialingCode: '48',
    isoCode: 'PL',
    continent: Continent.EU,
    capital: 'Warsaw',
    currency: 'PLN',
    languages: ["pl"],
    emoji: '🇵🇱',
    emojiUnicode: 'U+1F1F5 U+1F1F1',
  );
  static const Country PM = Country(
    name: 'Saint Pierre and Miquelon',
    nativeName: 'Saint-Pierre-et-Miquelon',
    dialingCode: '508',
    isoCode: 'PM',
    continent: Continent.NA,
    capital: 'Saint-Pierre',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇵🇲',
    emojiUnicode: 'U+1F1F5 U+1F1F2',
  );
  static const Country PN = Country(
    name: 'Pitcairn Islands',
    nativeName: 'Pitcairn Islands',
    dialingCode: '64',
    isoCode: 'PN',
    continent: Continent.OC,
    capital: 'Adamstown',
    currency: 'NZD',
    languages: ["en"],
    emoji: '🇵🇳',
    emojiUnicode: 'U+1F1F5 U+1F1F3',
  );
  static const Country PR = Country(
    name: 'Puerto Rico',
    nativeName: 'Puerto Rico',
    dialingCode: '1787,1939',
    isoCode: 'PR',
    continent: Continent.NA,
    capital: 'San Juan',
    currency: 'USD',
    languages: ["es", "en"],
    emoji: '🇵🇷',
    emojiUnicode: 'U+1F1F5 U+1F1F7',
  );
  static const Country PS = Country(
    name: 'Palestine',
    nativeName: 'فلسطين',
    dialingCode: '970',
    isoCode: 'PS',
    continent: Continent.AS,
    capital: 'Ramallah',
    currency: 'ILS',
    languages: ["ar"],
    emoji: '🇵🇸',
    emojiUnicode: 'U+1F1F5 U+1F1F8',
  );
  static const Country PT = Country(
    name: 'Portugal',
    nativeName: 'Portugal',
    dialingCode: '351',
    isoCode: 'PT',
    continent: Continent.EU,
    capital: 'Lisbon',
    currency: 'EUR',
    languages: ["pt"],
    emoji: '🇵🇹',
    emojiUnicode: 'U+1F1F5 U+1F1F9',
  );
  static const Country PW = Country(
    name: 'Palau',
    nativeName: 'Palau',
    dialingCode: '680',
    isoCode: 'PW',
    continent: Continent.OC,
    capital: 'Ngerulmud',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇵🇼',
    emojiUnicode: 'U+1F1F5 U+1F1FC',
  );
  static const Country PY = Country(
    name: 'Paraguay',
    nativeName: 'Paraguay',
    dialingCode: '595',
    isoCode: 'PY',
    continent: Continent.SA,
    capital: 'Asunción',
    currency: 'PYG',
    languages: ["es", "gn"],
    emoji: '🇵🇾',
    emojiUnicode: 'U+1F1F5 U+1F1FE',
  );
  static const Country QA = Country(
    name: 'Qatar',
    nativeName: 'قطر',
    dialingCode: '974',
    isoCode: 'QA',
    continent: Continent.AS,
    capital: 'Doha',
    currency: 'QAR',
    languages: ["ar"],
    emoji: '🇶🇦',
    emojiUnicode: 'U+1F1F6 U+1F1E6',
  );
  static const Country RE = Country(
    name: 'Réunion',
    nativeName: 'La Réunion',
    dialingCode: '262',
    isoCode: 'RE',
    continent: Continent.AF,
    capital: 'Saint-Denis',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇷🇪',
    emojiUnicode: 'U+1F1F7 U+1F1EA',
  );
  static const Country RO = Country(
    name: 'Romania',
    nativeName: 'România',
    dialingCode: '40',
    isoCode: 'RO',
    continent: Continent.EU,
    capital: 'Bucharest',
    currency: 'RON',
    languages: ["ro"],
    emoji: '🇷🇴',
    emojiUnicode: 'U+1F1F7 U+1F1F4',
  );
  static const Country RS = Country(
    name: 'Serbia',
    nativeName: 'Србија',
    dialingCode: '381',
    isoCode: 'RS',
    continent: Continent.EU,
    capital: 'Belgrade',
    currency: 'RSD',
    languages: ["sr"],
    emoji: '🇷🇸',
    emojiUnicode: 'U+1F1F7 U+1F1F8',
  );
  static const Country RU = Country(
    name: 'Russia',
    nativeName: 'Россия',
    dialingCode: '7',
    isoCode: 'RU',
    continent: Continent.EU,
    capital: 'Moscow',
    currency: 'RUB',
    languages: ["ru"],
    emoji: '🇷🇺',
    emojiUnicode: 'U+1F1F7 U+1F1FA',
  );
  static const Country RW = Country(
    name: 'Rwanda',
    nativeName: 'Rwanda',
    dialingCode: '250',
    isoCode: 'RW',
    continent: Continent.AF,
    capital: 'Kigali',
    currency: 'RWF',
    languages: ["rw", "en", "fr"],
    emoji: '🇷🇼',
    emojiUnicode: 'U+1F1F7 U+1F1FC',
  );
  static const Country SA = Country(
    name: 'Saudi Arabia',
    nativeName: 'العربية السعودية',
    dialingCode: '966',
    isoCode: 'SA',
    continent: Continent.AS,
    capital: 'Riyadh',
    currency: 'SAR',
    languages: ["ar"],
    emoji: '🇸🇦',
    emojiUnicode: 'U+1F1F8 U+1F1E6',
  );
  static const Country SB = Country(
    name: 'Solomon Islands',
    nativeName: 'Solomon Islands',
    dialingCode: '677',
    isoCode: 'SB',
    continent: Continent.OC,
    capital: 'Honiara',
    currency: 'SBD',
    languages: ["en"],
    emoji: '🇸🇧',
    emojiUnicode: 'U+1F1F8 U+1F1E7',
  );
  static const Country SC = Country(
    name: 'Seychelles',
    nativeName: 'Seychelles',
    dialingCode: '248',
    isoCode: 'SC',
    continent: Continent.AF,
    capital: 'Victoria',
    currency: 'SCR',
    languages: ["fr", "en"],
    emoji: '🇸🇨',
    emojiUnicode: 'U+1F1F8 U+1F1E8',
  );
  static const Country SD = Country(
    name: 'Sudan',
    nativeName: 'السودان',
    dialingCode: '249',
    isoCode: 'SD',
    continent: Continent.AF,
    capital: 'Khartoum',
    currency: 'SDG',
    languages: ["ar", "en"],
    emoji: '🇸🇩',
    emojiUnicode: 'U+1F1F8 U+1F1E9',
  );
  static const Country SE = Country(
    name: 'Sweden',
    nativeName: 'Sverige',
    dialingCode: '46',
    isoCode: 'SE',
    continent: Continent.EU,
    capital: 'Stockholm',
    currency: 'SEK',
    languages: ["sv"],
    emoji: '🇸🇪',
    emojiUnicode: 'U+1F1F8 U+1F1EA',
  );
  static const Country SG = Country(
    name: 'Singapore',
    nativeName: 'Singapore',
    dialingCode: '65',
    isoCode: 'SG',
    continent: Continent.AS,
    capital: 'Singapore',
    currency: 'SGD',
    languages: ["en", "ms", "ta", "zh"],
    emoji: '🇸🇬',
    emojiUnicode: 'U+1F1F8 U+1F1EC',
  );
  static const Country SH = Country(
    name: 'Saint Helena',
    nativeName: 'Saint Helena',
    dialingCode: '290',
    isoCode: 'SH',
    continent: Continent.AF,
    capital: 'Jamestown',
    currency: 'SHP',
    languages: ["en"],
    emoji: '🇸🇭',
    emojiUnicode: 'U+1F1F8 U+1F1ED',
  );
  static const Country SI = Country(
    name: 'Slovenia',
    nativeName: 'Slovenija',
    dialingCode: '386',
    isoCode: 'SI',
    continent: Continent.EU,
    capital: 'Ljubljana',
    currency: 'EUR',
    languages: ["sl"],
    emoji: '🇸🇮',
    emojiUnicode: 'U+1F1F8 U+1F1EE',
  );
  static const Country SJ = Country(
    name: 'Svalbard and Jan Mayen',
    nativeName: 'Svalbard og Jan Mayen',
    dialingCode: '4779',
    isoCode: 'SJ',
    continent: Continent.EU,
    capital: 'Longyearbyen',
    currency: 'NOK',
    languages: ["no"],
    emoji: '🇸🇯',
    emojiUnicode: 'U+1F1F8 U+1F1EF',
  );
  static const Country SK = Country(
    name: 'Slovakia',
    nativeName: 'Slovensko',
    dialingCode: '421',
    isoCode: 'SK',
    continent: Continent.EU,
    capital: 'Bratislava',
    currency: 'EUR',
    languages: ["sk"],
    emoji: '🇸🇰',
    emojiUnicode: 'U+1F1F8 U+1F1F0',
  );
  static const Country SL = Country(
    name: 'Sierra Leone',
    nativeName: 'Sierra Leone',
    dialingCode: '232',
    isoCode: 'SL',
    continent: Continent.AF,
    capital: 'Freetown',
    currency: 'SLL',
    languages: ["en"],
    emoji: '🇸🇱',
    emojiUnicode: 'U+1F1F8 U+1F1F1',
  );
  static const Country SM = Country(
    name: 'San Marino',
    nativeName: 'San Marino',
    dialingCode: '378',
    isoCode: 'SM',
    continent: Continent.EU,
    capital: 'City of San Marino',
    currency: 'EUR',
    languages: ["it"],
    emoji: '🇸🇲',
    emojiUnicode: 'U+1F1F8 U+1F1F2',
  );
  static const Country SN = Country(
    name: 'Senegal',
    nativeName: 'Sénégal',
    dialingCode: '221',
    isoCode: 'SN',
    continent: Continent.AF,
    capital: 'Dakar',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇸🇳',
    emojiUnicode: 'U+1F1F8 U+1F1F3',
  );
  static const Country SO = Country(
    name: 'Somalia',
    nativeName: 'Soomaaliya',
    dialingCode: '252',
    isoCode: 'SO',
    continent: Continent.AF,
    capital: 'Mogadishu',
    currency: 'SOS',
    languages: ["so", "ar"],
    emoji: '🇸🇴',
    emojiUnicode: 'U+1F1F8 U+1F1F4',
  );
  static const Country SR = Country(
    name: 'Suriname',
    nativeName: 'Suriname',
    dialingCode: '597',
    isoCode: 'SR',
    continent: Continent.SA,
    capital: 'Paramaribo',
    currency: 'SRD',
    languages: ["nl"],
    emoji: '🇸🇷',
    emojiUnicode: 'U+1F1F8 U+1F1F7',
  );
  static const Country SS = Country(
    name: 'South Sudan',
    nativeName: 'South Sudan',
    dialingCode: '211',
    isoCode: 'SS',
    continent: Continent.AF,
    capital: 'Juba',
    currency: 'SSP',
    languages: ["en"],
    emoji: '🇸🇸',
    emojiUnicode: 'U+1F1F8 U+1F1F8',
  );
  static const Country ST = Country(
    name: 'São Tomé and Príncipe',
    nativeName: 'São Tomé e Príncipe',
    dialingCode: '239',
    isoCode: 'ST',
    continent: Continent.AF,
    capital: 'São Tomé',
    currency: 'STN',
    languages: ["pt"],
    emoji: '🇸🇹',
    emojiUnicode: 'U+1F1F8 U+1F1F9',
  );
  static const Country SV = Country(
    name: 'El Salvador',
    nativeName: 'El Salvador',
    dialingCode: '503',
    isoCode: 'SV',
    continent: Continent.NA,
    capital: 'San Salvador',
    currency: 'SVC,USD',
    languages: ["es"],
    emoji: '🇸🇻',
    emojiUnicode: 'U+1F1F8 U+1F1FB',
  );
  static const Country SX = Country(
    name: 'Sint Maarten',
    nativeName: 'Sint Maarten',
    dialingCode: '1721',
    isoCode: 'SX',
    continent: Continent.NA,
    capital: 'Philipsburg',
    currency: 'ANG',
    languages: ["nl", "en"],
    emoji: '🇸🇽',
    emojiUnicode: 'U+1F1F8 U+1F1FD',
  );
  static const Country SY = Country(
    name: 'Syria',
    nativeName: 'سوريا',
    dialingCode: '963',
    isoCode: 'SY',
    continent: Continent.AS,
    capital: 'Damascus',
    currency: 'SYP',
    languages: ["ar"],
    emoji: '🇸🇾',
    emojiUnicode: 'U+1F1F8 U+1F1FE',
  );
  static const Country SZ = Country(
    name: 'Swaziland',
    nativeName: 'Swaziland',
    dialingCode: '268',
    isoCode: 'SZ',
    continent: Continent.AF,
    capital: 'Lobamba',
    currency: 'SZL',
    languages: ["en", "ss"],
    emoji: '🇸🇿',
    emojiUnicode: 'U+1F1F8 U+1F1FF',
  );
  static const Country TC = Country(
    name: 'Turks and Caicos Islands',
    nativeName: 'Turks and Caicos Islands',
    dialingCode: '1649',
    isoCode: 'TC',
    continent: Continent.NA,
    capital: 'Cockburn Town',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇹🇨',
    emojiUnicode: 'U+1F1F9 U+1F1E8',
  );
  static const Country TD = Country(
    name: 'Chad',
    nativeName: 'Tchad',
    dialingCode: '235',
    isoCode: 'TD',
    continent: Continent.AF,
    capital: 'N\'Djamena',
    currency: 'XAF',
    languages: ["fr", "ar"],
    emoji: '🇹🇩',
    emojiUnicode: 'U+1F1F9 U+1F1E9',
  );
  static const Country TF = Country(
    name: 'French Southern Territories',
    nativeName: 'Territoire des Terres australes et antarctiques fr',
    dialingCode: '262',
    isoCode: 'TF',
    continent: Continent.AN,
    capital: 'Port-aux-Français',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇹🇫',
    emojiUnicode: 'U+1F1F9 U+1F1EB',
  );
  static const Country TG = Country(
    name: 'Togo',
    nativeName: 'Togo',
    dialingCode: '228',
    isoCode: 'TG',
    continent: Continent.AF,
    capital: 'Lomé',
    currency: 'XOF',
    languages: ["fr"],
    emoji: '🇹🇬',
    emojiUnicode: 'U+1F1F9 U+1F1EC',
  );
  static const Country TH = Country(
    name: 'Thailand',
    nativeName: 'ประเทศไทย',
    dialingCode: '66',
    isoCode: 'TH',
    continent: Continent.AS,
    capital: 'Bangkok',
    currency: 'THB',
    languages: ["th"],
    emoji: '🇹🇭',
    emojiUnicode: 'U+1F1F9 U+1F1ED',
  );
  static const Country TJ = Country(
    name: 'Tajikistan',
    nativeName: 'Тоҷикистон',
    dialingCode: '992',
    isoCode: 'TJ',
    continent: Continent.AS,
    capital: 'Dushanbe',
    currency: 'TJS',
    languages: ["tg", "ru"],
    emoji: '🇹🇯',
    emojiUnicode: 'U+1F1F9 U+1F1EF',
  );
  static const Country TK = Country(
    name: 'Tokelau',
    nativeName: 'Tokelau',
    dialingCode: '690',
    isoCode: 'TK',
    continent: Continent.OC,
    capital: 'Fakaofo',
    currency: 'NZD',
    languages: ["en"],
    emoji: '🇹🇰',
    emojiUnicode: 'U+1F1F9 U+1F1F0',
  );
  static const Country TL = Country(
    name: 'East Timor',
    nativeName: 'Timor-Leste',
    dialingCode: '670',
    isoCode: 'TL',
    continent: Continent.OC,
    capital: 'Dili',
    currency: 'USD',
    languages: ["pt"],
    emoji: '🇹🇱',
    emojiUnicode: 'U+1F1F9 U+1F1F1',
  );
  static const Country TM = Country(
    name: 'Turkmenistan',
    nativeName: 'Türkmenistan',
    dialingCode: '993',
    isoCode: 'TM',
    continent: Continent.AS,
    capital: 'Ashgabat',
    currency: 'TMT',
    languages: ["tk", "ru"],
    emoji: '🇹🇲',
    emojiUnicode: 'U+1F1F9 U+1F1F2',
  );
  static const Country TN = Country(
    name: 'Tunisia',
    nativeName: 'تونس',
    dialingCode: '216',
    isoCode: 'TN',
    continent: Continent.AF,
    capital: 'Tunis',
    currency: 'TND',
    languages: ["ar"],
    emoji: '🇹🇳',
    emojiUnicode: 'U+1F1F9 U+1F1F3',
  );
  static const Country TO = Country(
    name: 'Tonga',
    nativeName: 'Tonga',
    dialingCode: '676',
    isoCode: 'TO',
    continent: Continent.OC,
    capital: 'Nuku\'alofa',
    currency: 'TOP',
    languages: ["en", "to"],
    emoji: '🇹🇴',
    emojiUnicode: 'U+1F1F9 U+1F1F4',
  );
  static const Country TR = Country(
    name: 'Turkey',
    nativeName: 'Türkiye',
    dialingCode: '90',
    isoCode: 'TR',
    continent: Continent.AS,
    capital: 'Ankara',
    currency: 'TRY',
    languages: ["tr"],
    emoji: '🇹🇷',
    emojiUnicode: 'U+1F1F9 U+1F1F7',
  );
  static const Country TT = Country(
    name: 'Trinidad and Tobago',
    nativeName: 'Trinidad and Tobago',
    dialingCode: '1868',
    isoCode: 'TT',
    continent: Continent.NA,
    capital: 'Port of Spain',
    currency: 'TTD',
    languages: ["en"],
    emoji: '🇹🇹',
    emojiUnicode: 'U+1F1F9 U+1F1F9',
  );
  static const Country TV = Country(
    name: 'Tuvalu',
    nativeName: 'Tuvalu',
    dialingCode: '688',
    isoCode: 'TV',
    continent: Continent.OC,
    capital: 'Funafuti',
    currency: 'AUD',
    languages: ["en"],
    emoji: '🇹🇻',
    emojiUnicode: 'U+1F1F9 U+1F1FB',
  );
  static const Country TW = Country(
    name: 'Taiwan',
    nativeName: '臺灣',
    dialingCode: '886',
    isoCode: 'TW',
    continent: Continent.AS,
    capital: 'Taipei',
    currency: 'TWD',
    languages: ["zh"],
    emoji: '🇹🇼',
    emojiUnicode: 'U+1F1F9 U+1F1FC',
  );
  static const Country TZ = Country(
    name: 'Tanzania',
    nativeName: 'Tanzania',
    dialingCode: '255',
    isoCode: 'TZ',
    continent: Continent.AF,
    capital: 'Dodoma',
    currency: 'TZS',
    languages: ["sw", "en"],
    emoji: '🇹🇿',
    emojiUnicode: 'U+1F1F9 U+1F1FF',
  );
  static const Country UA = Country(
    name: 'Ukraine',
    nativeName: 'Україна',
    dialingCode: '380',
    isoCode: 'UA',
    continent: Continent.EU,
    capital: 'Kyiv',
    currency: 'UAH',
    languages: ["uk"],
    emoji: '🇺🇦',
    emojiUnicode: 'U+1F1FA U+1F1E6',
  );
  static const Country UG = Country(
    name: 'Uganda',
    nativeName: 'Uganda',
    dialingCode: '256',
    isoCode: 'UG',
    continent: Continent.AF,
    capital: 'Kampala',
    currency: 'UGX',
    languages: ["en", "sw"],
    emoji: '🇺🇬',
    emojiUnicode: 'U+1F1FA U+1F1EC',
  );
  static const Country UM = Country(
    name: 'U.S. Minor Outlying Islands',
    nativeName: 'United States Minor Outlying Islands',
    dialingCode: '1',
    isoCode: 'UM',
    continent: Continent.OC,
    capital: '',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇺🇲',
    emojiUnicode: 'U+1F1FA U+1F1F2',
  );
  static const Country US = Country(
    name: 'United States',
    nativeName: 'United States',
    dialingCode: '1',
    isoCode: 'US',
    continent: Continent.NA,
    capital: 'Washington D.C.',
    currency: 'USD,USN,USS',
    languages: ["en"],
    emoji: '🇺🇸',
    emojiUnicode: 'U+1F1FA U+1F1F8',
  );
  static const Country UY = Country(
    name: 'Uruguay',
    nativeName: 'Uruguay',
    dialingCode: '598',
    isoCode: 'UY',
    continent: Continent.SA,
    capital: 'Montevideo',
    currency: 'UYI,UYU',
    languages: ["es"],
    emoji: '🇺🇾',
    emojiUnicode: 'U+1F1FA U+1F1FE',
  );
  static const Country UZ = Country(
    name: 'Uzbekistan',
    nativeName: 'O‘zbekiston',
    dialingCode: '998',
    isoCode: 'UZ',
    continent: Continent.AS,
    capital: 'Tashkent',
    currency: 'UZS',
    languages: ["uz", "ru"],
    emoji: '🇺🇿',
    emojiUnicode: 'U+1F1FA U+1F1FF',
  );
  static const Country VA = Country(
    name: 'Vatican City',
    nativeName: 'Vaticano',
    dialingCode: '39066,379',
    isoCode: 'VA',
    continent: Continent.EU,
    capital: 'Vatican City',
    currency: 'EUR',
    languages: ["it", "la"],
    emoji: '🇻🇦',
    emojiUnicode: 'U+1F1FB U+1F1E6',
  );
  static const Country VC = Country(
    name: 'Saint Vincent and the Grenadines',
    nativeName: 'Saint Vincent and the Grenadines',
    dialingCode: '1784',
    isoCode: 'VC',
    continent: Continent.NA,
    capital: 'Kingstown',
    currency: 'XCD',
    languages: ["en"],
    emoji: '🇻🇨',
    emojiUnicode: 'U+1F1FB U+1F1E8',
  );
  static const Country VE = Country(
    name: 'Venezuela',
    nativeName: 'Venezuela',
    dialingCode: '58',
    isoCode: 'VE',
    continent: Continent.SA,
    capital: 'Caracas',
    currency: 'VES',
    languages: ["es"],
    emoji: '🇻🇪',
    emojiUnicode: 'U+1F1FB U+1F1EA',
  );
  static const Country VG = Country(
    name: 'British Virgin Islands',
    nativeName: 'British Virgin Islands',
    dialingCode: '1284',
    isoCode: 'VG',
    continent: Continent.NA,
    capital: 'Road Town',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇻🇬',
    emojiUnicode: 'U+1F1FB U+1F1EC',
  );
  static const Country VI = Country(
    name: 'U.S. Virgin Islands',
    nativeName: 'United States Virgin Islands',
    dialingCode: '1340',
    isoCode: 'VI',
    continent: Continent.NA,
    capital: 'Charlotte Amalie',
    currency: 'USD',
    languages: ["en"],
    emoji: '🇻🇮',
    emojiUnicode: 'U+1F1FB U+1F1EE',
  );
  static const Country VN = Country(
    name: 'Vietnam',
    nativeName: 'Việt Nam',
    dialingCode: '84',
    isoCode: 'VN',
    continent: Continent.AS,
    capital: 'Hanoi',
    currency: 'VND',
    languages: ["vi"],
    emoji: '🇻🇳',
    emojiUnicode: 'U+1F1FB U+1F1F3',
  );
  static const Country VU = Country(
    name: 'Vanuatu',
    nativeName: 'Vanuatu',
    dialingCode: '678',
    isoCode: 'VU',
    continent: Continent.OC,
    capital: 'Port Vila',
    currency: 'VUV',
    languages: ["bi", "en", "fr"],
    emoji: '🇻🇺',
    emojiUnicode: 'U+1F1FB U+1F1FA',
  );
  static const Country WF = Country(
    name: 'Wallis and Futuna',
    nativeName: 'Wallis et Futuna',
    dialingCode: '681',
    isoCode: 'WF',
    continent: Continent.OC,
    capital: 'Mata-Utu',
    currency: 'XPF',
    languages: ["fr"],
    emoji: '🇼🇫',
    emojiUnicode: 'U+1F1FC U+1F1EB',
  );
  static const Country WS = Country(
    name: 'Samoa',
    nativeName: 'Samoa',
    dialingCode: '685',
    isoCode: 'WS',
    continent: Continent.OC,
    capital: 'Apia',
    currency: 'WST',
    languages: ["sm", "en"],
    emoji: '🇼🇸',
    emojiUnicode: 'U+1F1FC U+1F1F8',
  );
  static const Country XK = Country(
    name: 'Kosovo',
    nativeName: 'Republika e Kosovës',
    dialingCode: '377,381,383,386',
    isoCode: 'XK',
    continent: Continent.EU,
    capital: 'Pristina',
    currency: 'EUR',
    languages: ["sq", "sr"],
    emoji: '🇽🇰',
    emojiUnicode: 'U+1F1FD U+1F1F0',
  );
  static const Country YE = Country(
    name: 'Yemen',
    nativeName: 'اليَمَن',
    dialingCode: '967',
    isoCode: 'YE',
    continent: Continent.AS,
    capital: 'Sana\'a',
    currency: 'YER',
    languages: ["ar"],
    emoji: '🇾🇪',
    emojiUnicode: 'U+1F1FE U+1F1EA',
  );
  static const Country YT = Country(
    name: 'Mayotte',
    nativeName: 'Mayotte',
    dialingCode: '262',
    isoCode: 'YT',
    continent: Continent.AF,
    capital: 'Mamoudzou',
    currency: 'EUR',
    languages: ["fr"],
    emoji: '🇾🇹',
    emojiUnicode: 'U+1F1FE U+1F1F9',
  );
  static const Country ZA = Country(
    name: 'South Africa',
    nativeName: 'South Africa',
    dialingCode: '27',
    isoCode: 'ZA',
    continent: Continent.AF,
    capital: 'Pretoria',
    currency: 'ZAR',
    languages: ["af", "en", "nr", "st", "ss", "tn", "ts", "ve", "xh", "zu"],
    emoji: '🇿🇦',
    emojiUnicode: 'U+1F1FF U+1F1E6',
  );
  static const Country ZM = Country(
    name: 'Zambia',
    nativeName: 'Zambia',
    dialingCode: '260',
    isoCode: 'ZM',
    continent: Continent.AF,
    capital: 'Lusaka',
    currency: 'ZMK',
    languages: ["en"],
    emoji: '🇿🇲',
    emojiUnicode: 'U+1F1FF U+1F1F2',
  );
  static const Country ZW = Country(
    name: 'Zimbabwe',
    nativeName: 'Zimbabwe',
    dialingCode: '263',
    isoCode: 'ZW',
    continent: Continent.AF,
    capital: 'Harare',
    currency: 'USD,ZAR,BWP,GBP,AUD,CNY,INR,JPY',
    languages: ["en", "sn", "nd"],
    emoji: '🇿🇼',
    emojiUnicode: 'U+1F1FF U+1F1FC',
  );

  /// All the countries in the picker list
  static const ALL = <Country>[
    AD,
    AE,
    AF,
    AG,
    AI,
    AL,
    AM,
    AO,
    AQ,
    AR,
    AS,
    AT,
    AU,
    AW,
    AX,
    AZ,
    BA,
    BB,
    BD,
    BE,
    BF,
    BG,
    BH,
    BI,
    BJ,
    BL,
    BM,
    BN,
    BO,
    BQ,
    BR,
    BS,
    BT,
    BV,
    BW,
    BY,
    BZ,
    CA,
    CC,
    CD,
    CF,
    CG,
    CH,
    CI,
    CK,
    CL,
    CM,
    CN,
    CO,
    CR,
    CU,
    CV,
    CW,
    CX,
    CY,
    CZ,
    DE,
    DJ,
    DK,
    DM,
    DO,
    DZ,
    EC,
    EE,
    EG,
    EH,
    ER,
    ES,
    ET,
    FI,
    FJ,
    FK,
    FM,
    FO,
    FR,
    GA,
    GB,
    GD,
    GE,
    GF,
    GG,
    GH,
    GI,
    GL,
    GM,
    GN,
    GP,
    GQ,
    GR,
    GS,
    GT,
    GU,
    GW,
    GY,
    HK,
    HM,
    HN,
    HR,
    HT,
    HU,
    ID,
    IE,
    IL,
    IM,
    IN,
    IO,
    IQ,
    IR,
    IS,
    IT,
    JE,
    JM,
    JO,
    JP,
    KE,
    KG,
    KH,
    KI,
    KM,
    KN,
    KP,
    KR,
    KW,
    KY,
    KZ,
    LA,
    LB,
    LC,
    LI,
    LK,
    LR,
    LS,
    LT,
    LU,
    LV,
    LY,
    MA,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MK,
    ML,
    MM,
    MN,
    MO,
    MP,
    MQ,
    MR,
    MS,
    MT,
    MU,
    MV,
    MW,
    MX,
    MY,
    MZ,
    NA,
    NC,
    NE,
    NF,
    NG,
    NI,
    NL,
    NO,
    NP,
    NR,
    NU,
    NZ,
    OM,
    PA,
    PE,
    PF,
    PG,
    PH,
    PK,
    PL,
    PM,
    PN,
    PR,
    PS,
    PT,
    PW,
    PY,
    QA,
    RE,
    RO,
    RS,
    RU,
    RW,
    SA,
    SB,
    SC,
    SD,
    SE,
    SG,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SR,
    SS,
    ST,
    SV,
    SX,
    SY,
    SZ,
    TC,
    TD,
    TF,
    TG,
    TH,
    TJ,
    TK,
    TL,
    TM,
    TN,
    TO,
    TR,
    TT,
    TV,
    TW,
    TZ,
    UA,
    UG,
    UM,
    US,
    UY,
    UZ,
    VA,
    VC,
    VE,
    VG,
    VI,
    VN,
    VU,
    WF,
    WS,
    YE,
    YT,
    ZA,
    ZM,
    ZW,
  ];

  /// returns an country with the specified [isoCode] or ```null``` if
  /// none or more than 1 are found
  static findByIsoCode(String? isoCode) {
    return ALL.singleWhere(
      (item) => item.isoCode == isoCode,
      orElse: () => Country.IN,
    );
  }

  /// returns an country with the specified [isoCode] or ```null``` if
  /// none or more than 1 are found
  static findByDialingCode(String? dialingCode) {
    return ALL.singleWhere(
      (item) => item.dialingCode == dialingCode,
    );
  }

  @override
  int get hashCode => super.hashCode;
}
